// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLySanPham.Models;

#nullable disable

namespace QuanLySanPham.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422162356_AddQuantityAndDescriptionToProduct")]
    partial class AddQuantityAndDescriptionToProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLySanPham.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sản phẩm 1",
                            Price = 100.0,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sản phẩm 2",
                            Price = 200.0,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sản phẩm 3",
                            Price = 300.0,
                            Quantity = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
